✨ [FEAT] 내가 작성한 후기글 수정 기능 구현
TeamNado-Sunbae/NadoSunbae-iOS pull request #193
Opened 2022-02-18 16:19 UTC by jane1choi

## 🍎 관련 이슈
closed #183

## 🍎 변경 사항 및 이유
- 후기글 수정 기능을 구현했습니다.

## 🍎 PR Point
- 후기 상세뷰에서 후기 작성 뷰로 화면 전환 시 데이터를 전달하여 이전에 작성한 내용이 해당 `textView`에 보이도록 했습니다.
- 후기 작성 상황과 달리 수정 시에는 뷰가 그려질 때 이미 `textView`에 `text`가 있기 때문에 기존 `textViewDidChange()` 에 있던 조건문 코드를 밖으로 빼서 함수화 시키고, `viewWillAppear()`와 `textViewDidChange()`에서 호출하였습니다. 
- 또한 `placeholder` 값을 텍스트로 인식하지 않도록 하기 위해 완료 버튼 활성화 코드를 변경하였습니다.
- x버튼 클릭 시 나타나는 알럿 메시지를 분기처리해주었습니다. 

    **클라에서 더미 관리 SSAP POSSIBLE**

## 📸 ScreenShot
- 수정 플로우

https://user-images.githubusercontent.com/63277563/154719532-95839c09-d4ee-4b83-a2f8-18aef0826b92.mp4

- 후기글 수정 상황에서 x버튼 클릭 시

https://user-images.githubusercontent.com/63277563/154721008-6178ecad-ee86-4850-946c-224c836e9466.mp4

2022-02-18 16:33 UTC, dev-madilyn approved these changes
고생많앗어. 스겜

2022-02-18 16:33 UTC, dev-madilyn commented on NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/ReviewService.swift
> +            return "/review-post/\(postID)"
왠지 이 _, _, _에서 분노가 느껴지네여

2022-02-18 16:33 UTC, dev-madilyn commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewDetailVC.swift
> +                        }
진짜 깔끔하고 enum 잘쓰셨네요

2022-02-18 16:33 UTC, dev-madilyn commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewDetailVC.swift
> +                        }
그런데 리팩토링할수있을것같애 더 쉽게
근데 이건 내가 제주도 갔다와서 고민해볼게..

2022-02-18 16:33 UTC, dev-madilyn commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewWriteVC.swift
> +        reviewWriteNaviBar.rightActivateBtn.isActivated = essentialTextViewStatus && choiceTextViewStatus
필사적으로 주석쓴거 넘 귀엽다
나 제주도갔다와서 언니 만약에 리팩토링하면 더 자세히볼게쏴리

2022-02-19 09:28 UTC, hwangJi-dev requested changes
고생해써어잉!! 벌써 수정까지한 숙주 최고양..
수정부분 alert 클릭시 리펙토링 관련 의견 남겨놓았으니 그부분 참고해서 의견 다시 남겨주세욧!!

2022-02-19 09:28 UTC, hwangJi-dev commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewDetailVC.swift
> +                        }
```
                    /// 후기 작성 뷰로 이동
                    let ReviewWriteSB = UIStoryboard.init(name: "ReviewWriteSB", bundle: nil)
                    guard let nextVC = ReviewWriteSB.instantiateViewController(withIdentifier: ReviewWriteVC.className) as? ReviewWriteVC else { return }
                    
                    /// 기존 작성 내용 전달
                    nextVC.isPosting = false
                    nextVC.oneLineReviewTextView.textColor = .mainText
                    nextVC.oneLineReviewTextView.text = self.detailPost.post.oneLineReview
                    
                    let contentTitleDict: [String : UITextView] = ["장단점" : nextVC.prosAndConsTextView, "뭘 배우나요?" : nextVC.learnInfoTextView, "추천 수업" : nextVC.recommendClassTextView, "비추 수업" :  nextVC.badClassTextView, "향후 진로" : nextVC.futureTextView, "꿀팁" : nextVC.tipTextView]
                    var newContentTitleDict = [String : UITextView]()
                    var newContentDict = [String : String]()
                    
                    for i in 0..<self.detailPost.post.contentList.count {
                        newContentTitleDict.updateValue(contentTitleDict[self.detailPost.post.contentList[i].title] ?? UITextView(), forKey: self.detailPost.post.contentList[i].title)
                        newContentDict.updateValue(self.detailPost.post.contentList[i].content, forKey: self.detailPost.post.contentList[i].title)
                    }
                    
                    newContentTitleDict.forEach {
                        $0.value.textColor = .mainText
                        // 딕셔너리는 array처럼 Index가 정적으로 저장되어있지 않기 때문에 for i - in 문을 사용하지 않고 forEach 문으로 해결하기 위해
                        // [title : content] dict를 새로 만들어서 해당 key값에 해당하는 value를 text에 지정해줌
                        $0.value.text = newContentDict[$0.key]
                    }
                    
                    nextVC.modalPresentationStyle = .fullScreen
                    self.present(nextVC, animated: true, completion: nil)
```

후 어제밤부터 이거 리펙토링 로직 좀 생각해보다가 머리가안돌아가서 구냥 잤는데 오늘 좀 머리굴려서 dictionary 사용한 해결책을 하나 들구와봤어!
일단 enum 쓴거 넘 깔끔하고 좋은데 enum case마다 같은 코드 2개가 반복돼가지구 이걸 리펙토링해보면 어떨까 했어!

리펙토링한 방법은
1. enum으로 case나눴던 contentTitle과 해당 쌍이 되는 textView를 dictionary 배열로 선언해주기 --> 해당 contentTitle마다 쌍이되는 textView가 있어서 dictionary를 써야겠다는 생각을 하게 되었음!
2. 원랜 filter를 쓰고 싶었으나 맘처럼 잘 안돼서 for문을 통해 detailPost의 contentList로 얻어온 값들을 let으로 선언해둔 쌍 dictionary를 참고해서 newContentTitleDict에 값을 넣어주었음 (--> 내가 쓴 title-content들만을 가진 새로운 키값 쌍 딕셔너리가 되겠지?) 
2-1.  딕셔너리는 array처럼 Index가 정적으로 저장되어있지 않기 때문에  [title : content] dict도 새로 만들어서(newContentDict) 해당 key값에 해당하는 value를 text에 지정해줌
3. newContentTitleDict에 forEach문을 사용해서 내가 썼던 title에 해당하는 모든 textView의 textColor를 mainText로 지정해주고, 내가 썼던 title에 해당하는 모든 textView의 text에 해당 text를 넣어주기 위해 key값을 이용해 값을 지정해주었음! (for-i-in 으로 하지 않은 이유는 딕셔너리는 array처럼 Index가 정적으로 저장되어있지 않기 때문에 i로 지정해주면 값이 달라질 수 있기 때문임!)

2022-02-19 09:28 UTC, hwangJi-dev commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewDetailVC.swift
> +                        }
이 로직 한번 참고해봐줭 ~~ ㅎ 그리고 nextVC 관련부분들 싹 함수로 한번 더 빼주면 더 좋을 것 같아!

2022-02-20 07:12 UTC, hwangJi-dev approved these changes
와앙 최고닷!!!!!!!!! 어프룹 콰오쾅쾅쾈ㅇ!!!!

2022-02-20 08:41 UTC, merged