✨ [FEAT] 과방탭 (1:1, 전체) 질문 원글 삭제 기능 구현
TeamNado-Sunbae/NadoSunbae-iOS pull request #217
Opened 2022-02-24 18:15 UTC by hwangJi-dev

## 🍎 관련 이슈
closed #215 

## 🍎 변경 사항 및 이유
- 좋아요 Service moyaTarget case명 수정 
- 질문글 내에서 질문(원글), 답변(댓글) 상태 분기처리를 위해 QnAType(enum) 추가

## 🍎 PR Point
- 질문글에는 ,, 아주 슬픈 전설이 있었으니 ,, 질문 스레드의 흰색 박스는 사실 질문원글, 질문자 댓글 셀을 같은 걸 사용합니다. 
- 댓글일 경우 titleLabel에 text가 없어서 sizeToFit을 통해 댓글 부분은 민트색 타이틀 글씨가 안보이게 되는 구런 눈속임을 갖구 있는데요,, 그래서 요 분기처리를 같은 cellForRowAt의 questionCell 내에서 indexPath가 0일경우 아닐경우로 분기처리를 해주고 있습니다!
- 근데 그  if-else문 안에서 또 alert함수를 코드로 if-else 마다 써줘야 하는 문제가 발생해서 중복되는 alert 생성 부분을 함수로 빼게 되었고 alert 코드 내에서 딕셔너리를 이용해서 QnAType에 따른 alertMsg를 짝으로 지어주었습니다. (사실은 같은 셀의 더보기 버튼의 삭제버튼을 누른거지만 질문 원글 삭제일 경우와 질문 댓글일 경우 alertMsg도 다르게 떠야할 것 같아서 이 부분을 분기처리 해주었습니다!)
- 그래서 현재 질문 원글 삭제 부분만 기능을 구현했구요! 질문 댓글 삭제 부분은 다른 API를 이용해야하기에 그 부분을 nil로 설정해둔 상태입니다! (TODO참고 🤗)

## 📸 ScreenShot
<img width=375 src="(https://user-images.githubusercontent.com/63224278/155583222-3200f7de-1896-4884-8a0a-d21578b19152.gif">

2022-02-24 18:28 UTC, jane1choi requested changes
주석만 확인 부탁드립니다~! 수고했어요!

2022-02-24 18:28 UTC, jane1choi commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift
> +        guard let alert = Bundle.main.loadNibNamed(NadoAlertVC.className, owner: self, options: nil)?.first as? NadoAlertVC else { return }
알럿 따로 함수로 뺀거 좋네요~!

2022-02-24 18:28 UTC, jane1choi commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift
> +            qnaType == .question ? self.requestDeletePostQuestion(postID: self.postID ?? 0) : nil
원글이랑 댓글 enum으로 구분했구나! 굳굳👍🏻

2022-02-24 18:28 UTC, jane1choi commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift
> +    /// 답변 수정 API 요청 메서드
요거 주석 삭제로 바꿔야될거 같네요!

2022-02-24 18:30 UTC, hwangJi-dev commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift
> +    /// 답변 수정 API 요청 메서드
아 대박 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 대박대박 얼른 고치러감 휘휘~~

2022-02-24 18:30 UTC, hwangJi-dev commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift
> +    /// 답변 수정 API 요청 메서드
무지성 복붙 들켜버렸당 .. ㅎㅅㅎ

2022-02-24 18:43 UTC, jane1choi commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift
> +    /// 답변 수정 API 요청 메서드
@hwangJi-dev ㅋㅎㅋㅎㅋㅎㅎㅋㅋㅋㅋ

2022-02-24 18:45 UTC, jane1choi approved these changes
확인했습니당~

2022-02-25 09:01 UTC, dev-madilyn approved these changes
역쉬 지은걸 CRUD 거의 다 되어가는 모습 보니까.....편안해지네여....... 수고했당

2022-02-25 09:01 UTC, dev-madilyn commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift
> +                            indexPath.row == 0 ? self.makeNadoDeleteAlert(qnaType: .question) : self.makeNadoDeleteAlert(qnaType: .comment)
`self.makeNadoDeleteAlert(qnaType: indexPath.row == 0 ? .question : .comment)`
이걸로 바꾸면 더 짧아질 것 같아여~~~!!!! 컨벤션은 아니라 참고만 😎

2022-02-25 12:16 UTC, merged