🔨[FIX] 후기 탭 QA 반영
TeamNado-Sunbae/NadoSunbae-iOS pull request #228
Opened 2022-02-27 15:37 UTC by jane1choi

## 🍎 관련 이슈
closed #226

## 🍎 변경 사항 및 이유
- 후기 탭 QA사항을 모두 반영했습니다.

## 🍎 PR Point
- 후기 메인 뷰 태그 셀 간격 조정
- 후기글 수정 시 이전 선택한 이미지가 아닌 디폴트 이미지 체크되는 버그 해결
(이전 선택 이미지에 체크 표시 뜨도록 수정)

## 📸 ScreenShot
- 구동영상

https://user-images.githubusercontent.com/63277563/155889029-c51b4068-cf9c-41f5-acaa-c3b1825c3766.mp4

2022-02-27 15:46 UTC, dev-madilyn approved these changes
확인해씀니다~ 수고했어 QA 모두 반영이라뉘

2022-02-27 15:46 UTC, dev-madilyn commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewWriteVC.swift
> +    var postBgImgID: Int = 6
컨벤션 맞춰 준 거 굿~

2022-02-27 15:46 UTC, dev-madilyn commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewWriteVC.swift
>      }
배경 이미지 여기서 받아서 세팅하는군!

2022-02-27 15:47 UTC, jane1choi commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewWriteVC.swift
>      }
@dev-madilyn 고냥 다같이 받아와버려~

2022-02-28 02:09 UTC, hwangJi-dev requested changes
앱잼때 비추수업이랑 뭐 하나만 간격안맞아서 고생했던거 생각나눼 ㅋㅋㅋ ㅠㅠㅠ 고생했엉!

2022-02-28 02:09 UTC, hwangJi-dev commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewWriteVC.swift
> +    func setReceivedData(status: Bool, postId: Int, bgImgId: Int) {
bgImgId도 컨벤션 맞춰서 bgImgID로 바꿔주면 어떨까요~?

2022-02-28 02:29 UTC, hwangJi-dev approved these changes
확인입니당 💜

2022-02-28 02:29 UTC, hwangJi-dev commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewWriteVC.swift
> +    var bgImgID: Int = 6
확인!!!!

2022-02-28 02:31 UTC, merged