✨ [FEAT] 마이페이지 비밀번호 재설정 뷰/API 구현
TeamNado-Sunbae/NadoSunbae-iOS pull request #243
Opened 2022-03-01 03:52 UTC by dev-madilyn

## 🍎 관련 이슈
closed #231

## 🍎 변경 사항 및 이유
* 비밀번호 재설정 플로우 구현(마이페이지, 로그인뷰 둘 다 사용 가능~!) 로그인뷰는 추후에 붙여야 함

## 🍎 PR Point
* 로그아웃 Service 코드 작성
* 비밀번호 재설정 Service 코드 작성
* 비밀번호 재설정 메일 전송 후 로그아웃 처리, 완료 버튼 누르면 로그인 화면으로 이동
* 근데 비밀번호 재설정 메일 전송 완료 화면에서, 재전송을 할 수 있어야 하는데 이때 accessToken이 필요함. 그래서 로그아웃 처리는 하되 accessToken은 UserDefaults에 남아 있는 상태입니다! 다시 로그인하면 덮어씌워질 거라서 ㅎㅎ

## 📸 ScreenShot

https://user-images.githubusercontent.com/43312096/156101583-6af6c752-6601-43f9-badd-40742b546f9f.MP4

2022-03-01 04:00 UTC, jane1choi requested changes
함수명 관련 리뷰만 한번 확인해조! 수고했엉
나도 알엑스 공부해야겄다...

2022-03-01 04:00 UTC, jane1choi commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ResetPW/VC/ResetPWVC.swift
> +        return UserDefaults.standard.value(forKey: UserDefaults.Keys.UserID) is Int ? true : false
오옹 요런식으로 하는구나 굿굿🔥

2022-03-01 06:53 UTC, hwangJi-dev requested changes
고생했어~~~ 코리 한번만 봐줭!

2022-03-01 06:53 UTC, hwangJi-dev commented on NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/MypageSettingAPI.swift
> +            return .serverErr
둘다 동일한 serverErr라서 case 401...500 으로 범위 설정해주고 코드 두줄로 줄이는게 어떨까요?

2022-03-02 14:40 UTC, dev-madilyn reviewed
..아이런

2022-03-02 14:40 UTC, dev-madilyn commented on NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/SignAPI.swift
> +    func signOut(completion: @escaping (NetworkResult<Any>) -> (Void)) {
@jane1choi 앗  `signIn`, `signUp`, `signOut`은 모두 `request` 빼고 함수 이름 지었는데(뭔가 고유명사같은 느낌이라,,), 다 `request` 붙여서 바꾸는 게 좋아 보이나여?? @hwangJi-dev 도 으ㅣ견 좀!!

2022-03-02 15:09 UTC, hwangJi-dev approved these changes
확인했슈~~~

2022-03-02 15:25 UTC, jane1choi approved these changes
굿굿 확인했습니다! 수고했어요💜

2022-03-02 15:25 UTC, merged