✨ [FEAT] 선배 개인페이지 학과 후기 UI 구성
TeamNado-Sunbae/NadoSunbae-iOS pull request #262
Opened 2022-03-04 14:17 UTC by jane1choi

## 🍎 관련 이슈
closed #256

## 🍎 변경 사항 및 이유
- 과방 탭의 선배 개인페이지 학과 후기 UI를 구성하였습니다.

## 🍎 PR Point
- 선배 개인페이지에서 최신순, 좋아요순 정렬을 바꾸었을때 서버통신 과정이 보이도록
loading indicator를 추가해주었습니다.
- 선배 개인페이지 학과 후기 버튼을 누르면 학과 리스트 뷰로 이동하도록 화면전환을 구현하였습니다.
- 학과 후기 버튼 클릭 시 정빈이가 마이페이지 학과 후기 뷰 구성 시 만들어놓았던 `MypageMyReviewVC`에서 
userID로 분기처리를 해서 해당 선배가 쓴 글이 보일 수 있도록 구현하였습니다.

## 📸 ScreenShot
- 좋아요 클릭 시 LikeCount는 올라가지만 하트 이미지가 바뀌지 않는 문제

https://user-images.githubusercontent.com/63277563/156779112-db3be1cb-226d-422a-a214-9186140b32d8.mp4

- reviewList.isEmpty일 경우 emptyView가 보이지 않는 문제

https://user-images.githubusercontent.com/63277563/156779211-54121ea5-e137-4d36-aa2f-8db826521aec.MP4

2022-03-04 17:56 UTC, hwangJi-dev approved these changes
삼항연산자로 분기처리한거 넘 멋있다 ><

2022-03-05 04:58 UTC, hwangJi-dev requested changes
컨벤션 관련 코리 한번만 확인해주세요!

2022-03-05 04:58 UTC, hwangJi-dev commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/VC/MypageMyReviewVC.swift
> +// MARK: - UITableViewDataSource
ㅎㅎ 굳

2022-03-05 04:58 UTC, hwangJi-dev commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/VC/MypageMyReviewVC.swift
> +    @IBOutlet weak var scrollView: UIScrollView!
컨벤션에 맞춰 mypageReviewSV 이런식으로 네이밍하는게 더 좋을 것 같아요!

2022-03-05 07:59 UTC, dev-madilyn approved these changes
오 돌려봤더니 잘된다 ><
무한스크롤 그거 내가 스보 짤 때 어처구니없게 짜서 그런듯....ㅎ먄
고생했서~

2022-03-05 10:45 UTC, hwangJi-dev approved these changes

2022-03-05 10:45 UTC, hwangJi-dev commented
아웅 체고다 확인확인 😉😉

2022-03-06 02:09 UTC, merged