✨ [FEAT] 내가 쓴 후기 UI + API
TeamNado-Sunbae/NadoSunbae-iOS pull request #458
Opened 2022-09-11 17:06 UTC by dev-madilyn

## 🍎 관련 이슈
closed #457

## 🍎 변경 사항 및 이유
* 내가 쓴 후기 navi bar title을 변경하였습니다.
* 내가 쓴 후기 API path, model을 수정하였습니다.
* Swager 사용을 위해 로그인 시 [access token을 콘솔에 출력하는 코드](https://github.com/TeamNado-Sunbae/NadoSunbae-iOS/commit/45022cbd3dd4d48171e56b4468496b7adf4a81e6)를 추가하였습니다. 
* MypageAPI를 은주언니가 해 준 judgeStatus 함수를 통해 리팩토링하였습니다~~~ 완전 깔끔 !!

## 📸 ScreenShot
![image](https://user-images.githubusercontent.com/43312096/189539869-867b4350-76f5-4e68-b14f-f84eae70f609.png)

2022-09-12 10:15 UTC, jane1choi requested changes
굿굿티비~
컨벤션 관련 리뷰한번만 확인해주세여~

2022-09-12 10:15 UTC, jane1choi commented on NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/MypageAPI.swift
>  }
👍🏻👍🏻👍🏻

2022-09-12 10:15 UTC, jane1choi commented on NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/MypageAPI.swift
> -extension MypageAPI {
잘가라..~

2022-09-12 10:15 UTC, jane1choi commented on NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Mypage/MypageMyReviewModel.swift
> +    var id: Int
요거 원래 컨벤션에 맞춰서 `ID`로 쓰는건 어떨까욤..~?

2022-09-12 10:15 UTC, jane1choi commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/AutoSignInVC.swift
> +                    }
체고당...🥺

2022-09-12 15:33 UTC, dev-madilyn commented
> 요거 원래 컨벤션에 맞춰서 ID로 쓰는건 어떨까욤..~?

@jane1choi 반영하여 수정하였습니다~!!!!! 꼬마워용

2022-09-14 12:59 UTC, jane1choi approved these changes
이제봤당ㅜㅠ 쏘리ㅠ
확인했습니다!!!

2022-09-19 01:23 UTC, hwangJi-dev approved these changes
고생해써~~ judge함수 빠지니까 훨씬 깔끔하고 좋다,,,

2022-09-20 02:23 UTC, merged