✨ [FEAT] 회원가입 UI + API 수정 (+ 로그인 UI)
TeamNado-Sunbae/NadoSunbae-iOS pull request #462
Opened 2022-09-13 13:09 UTC by dev-madilyn

## 🍎 관련 이슈
closed #459

## 🍎 변경 사항 및 이유
* 서울여대, 중앙대 추가 및 학교 선택할 시 선택되었던 전공 초기화
* 전공정보 기입 뷰(`SignUpMajorVC`) Rx로 리팩토링 + UI 최적화(for iPhone SE..)
* `HalfModalVC`를 상속받아 회원가입 시에만 사용하는 `SignUpModalVC` 생성
* 학교에 따른 이메일 도메인 받아오는 api 연결 및 회원정보 기입 뷰에 적용
* SignAPI 리팩토링(judge 삭제)
* 로그인 뷰 아이디 textField placeholder 수정 (고대 이메일 삭제)
* 안 쓰는 파일 및 주석 정리

## 🍎 PR Point
>  `HalfModalVC`를 상속받아 회원가입 시에만 사용하는 `SignUpModalVC` 생성

을 진행하면서 HalfModalVC에 있던 프로퍼티들 중에 private을 없앤 게 좀 있는데 은주언니 뭔가 문제될 거 있으면 말해조요!!
* 진짜 .,. 앱잼 초반에 했던 개똥같은 코드들 ............. 이해하느라 오래걸림 ㅎ
* 회원가입 및 로그인 관련은 이걸로 끝입니다 우하하

## 📸 ScreenShot

https://user-images.githubusercontent.com/43312096/189908911-a67b719a-ad86-4fba-aff6-38b4bc954c38.mov

2022-09-14 13:02 UTC, hwangJi-dev approved these changes
정빈아 고생했어! Rx 사용해서 리펙토링 한거 멋지당 ㅎㅎ

2022-09-14 13:46 UTC, jane1choi requested changes
브랜치 이동해서 스토리보드 확인했는데, IBAction연결 따로 해주면 굳이 `SignUpModalVC`를 생성해서 `HalfModalVC`내부를 바꿔주지 않아도 될 것 같아요! 
조금 귀찮은 작업이더라도 제가 만든 파일의 용도와 다르게 사용되고 있어서 바꿔주시면 감사하겠습니다!!!
필요하다면 타이틀 변경 메서드는 HalfModalVC()에 만들어두겠습니다!!

2022-09-20 10:24 UTC, jane1choi approved these changes
확인했습니당! 번거로웠을텐데 수고했어~!!

2022-09-20 10:24 UTC, jane1choi commented on NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Xib/MajorTVC.swift
>  }
굳굳!!

2022-09-20 10:24 UTC, jane1choi commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/SignUpMajorInfo/VC/SignUpMajorInfoVC.swift
> +
아주 조아용

2022-09-20 10:24 UTC, jane1choi commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/SignUpMajorInfo/VC/SignUpMajorInfoVC.swift
> +                    slideVC.vcType = .basic
분기처리 와웅..

2022-09-20 10:24 UTC, jane1choi commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/SignUpMajorInfo/VC/SignUpModalVC.swift
> +    var cellType: MajorCellType = .basic
확인했어염~

2022-09-20 10:24 UTC, jane1choi commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/SignUpMajorInfo/VC/SignUpModalVC.swift
> +                return cell
굳굳~

2022-09-20 10:28 UTC, merged