✨ [FEAT] 마이페이지 - 개인페이지 UI 구성
TeamNado-Sunbae/NadoSunbae-iOS pull request #48
Opened 2022-01-15 18:03 UTC by dev-madilyn

## 🍎 관련 이슈
closed #35

## 🍎 변경 사항 및 이유
* 마이페이지 - 개인페이지 UI 구성!
* 버튼 연결 안 된 것들이 많은데 다른 뷰로 넘어가는 버튼들이라~~

## 🍎 PR Point
* 여기 왤케 오래 걸렸지... 죄송함니다... 그럴 뷰는 아니엇는데.......
* 정숙한 Girl을 누르면 볼 수 있습니다~!!

## 📸 ScreenShot

https://user-images.githubusercontent.com/43312096/149632698-0e520e90-bbc9-4de4-a376-6b2db45579f8.MP4

2022-01-15 18:39 UTC, hwangJi-dev requested changes
컨벤션 관련해서 수정할 부분 코리에 달아뒀어요~~ 수고했다 정비니

2022-01-15 18:39 UTC, hwangJi-dev commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC.swift
> +    @IBOutlet weak var questionTableVIewHeight: NSLayoutConstraint!
###컨벤션선배 ### 
`questionTV, questionTVHeight`로 수정하는게 좋을 것 같아요~

2022-01-15 18:39 UTC, hwangJi-dev commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC.swift
> +
빈칸선배..!

2022-01-15 18:39 UTC, hwangJi-dev commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC.swift
> +    }
extension으로 UI 구분 넘 조와용

2022-01-16 04:23 UTC, dev-madilyn commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC.swift
> +
@hwangJi-dev 혹쉬 이건 어떤 부분 말하는 걸까여???! 우선 뎁스만큼 탭이 안 들어가 있는 부분이 있어서 추가함요... !!!

2022-01-16 04:54 UTC, hwangJi-dev commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC.swift
> +
내가보기엔 여기 밑에가 두줄 띄워져있었었는데 아니라면 넘어가줘요~

2022-01-16 05:58 UTC, hwangJi-dev approved these changes
므찌다 므쪄 정숙언니 ~ 👍🏻

2022-01-16 06:18 UTC, jane1choi approved these changes
수고하셨어 정빈걸~!~!😊🥰

2022-01-16 06:18 UTC, jane1choi commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageNVC/MypageNVC.swift
> +class MypageNVC: UINavigationController {
앗 나도 네비컨트롤러 만들어놨는데 그럼 한 파일만 남겨놔도 되려나..?
된다면 폴더링 요파일 Global로 빼놓는거 어떤가여??

2022-01-16 06:18 UTC, jane1choi commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC.swift
> +    }
왕 이거 신기선배...쇽샥 해가겠섭니다~~~👍🏻

2022-01-16 06:18 UTC, dev-madilyn commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC.swift
> +    }
@jane1choi 출처는 지은블로그~~😎

2022-01-16 06:22 UTC, dev-madilyn commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageNVC/MypageNVC.swift
> +class MypageNVC: UINavigationController {
나는 우선 폴더는 요렇게 빼놨구! 마이페이지 탭 내에서만 사용되는 NVC가 과연 전역으로 빼도 되는 것일지에 대한 의문이 있숴... 그래서 우선 Mypage 안에 넣었는데 이건 지은언니 의견도 물어보쟈!

![스크린샷 2022-01-16 오후 3 21 38](https://user-images.githubusercontent.com/43312096/149649701-577f0bc3-a910-4293-bcee-1e9edc17684f.png)

2022-01-16 06:24 UTC, merged