✅ [CHORE] 커뮤니티 글쓰기 관련 바텀시트 분기처리
TeamNado-Sunbae/NadoSunbae-iOS pull request #504
Opened 2022-10-05 15:41 UTC by jane1choi

## 🍎 관련 이슈
closed #495

## 🍎 변경 사항 및 이유
커뮤니티 글쓰기 뷰에서 필요한 바텀시트 UI에 맞게 커스텀할 수 있도록 코드를 수정하고 커뮤니티 글쓰기 통신을 완료하였습니다.

## 🍎 PR Point
- HalfModalVC의 타이틀을 커스텀할 수 있는 `setUpTitleLabel()` 메서드를 추가했습니다.
- 첫번째 셀이 '학과 무관' 일 경우, 즐겨찾기 기능이 해당 셀만 없기 때문에 학과 무관인 경우만 분기처리를 해주었습니다.
- 과방에서는 학과 무관 옵션 없이 학과 리스트만 뜨도록하기 위해 `ClassroomMainVC` `CommunityMainVC`에서 리스트가 다르게 들어가도록 학과 리스트를 받아오는 네트워크 코드를 수정했습니다.
- majorID를 넘겨주어 글쓰기 통신을 완료했습니다.
- ‼️ 글쓰기 완료 후 해당 뷰가 dismiss된 이후 리스트가 리로드가 안되는 문제가 있어 리로드 작업이 필요할 것 같습니다! (서버통신을 dismiss후 한번 더 해주는 것은 비효율적인 것 같아서 방법이 고민되어 일단 놔뒀습니다! @hwangJi-dev 한번 확인해주세요!)

## 📸 ScreenShot
- 과방 바텀시트와 커뮤니티 바텀시트 비교

https://user-images.githubusercontent.com/63277563/194101195-c6b2ef94-0883-4978-93ab-5c208e9b3a05.mp4

- 커뮤니티 글쓰기 기능 구현

https://user-images.githubusercontent.com/63277563/194102697-2206c801-a783-4753-a27e-cea046140ae9.mp4

2022-10-05 16:26 UTC, hwangJi-dev requested changes
로직 관련해서 궁금한 점을 코멘트해두었습니당!!! 답변 부탁드려요옹

2022-10-05 16:26 UTC, hwangJi-dev commented on NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Xib/MajorTVC.swift
> +        }
Cell에 데이터 넣어주는 부분이니까 재사용 문제도 있을 수 있어서 확실한 예외처리를 위해서 else구문도 써주는게 좋을것같아! 이 부분 삼항연산자 써도 좋을 것 같고!!

2022-10-05 16:26 UTC, hwangJi-dev commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Community/Reactor/CommunityMainReactor.swift
> +            return Observable.concat(self.requestMajorList(univID: 1, filterType: "all"))
요기 univID 정빈이가 UserDefaults에 저장해준 값으로 바꾸면 좋을듯!!

2022-10-05 16:26 UTC, hwangJi-dev commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Community/VC/CommunityMainVC.swift
> +        reactor?.action.onNext(.viewWillAppear)
학과 리스트 조회를 ViewDidAppear에서 보낸 이유와, Reactor의 액션명을 vidwWillAppear로 해준 이유가 궁금합니당 그리고 커뮤니티 메인에서 학과 리스트 조회를 호출해준 이유가 있나용>??

2022-10-05 16:34 UTC, hwangJi-dev commented
> * ‼️ 글쓰기 완료 후 해당 뷰가 dismiss된 이후 리스트가 리로드가 안되는 문제가 있어 리로드 작업이 필요할 것 같습니다! (서버통신을 dismiss후 한번 더 해주는 것은 비효율적인 것 같아서 방법이 고민되어 일단 놔뒀습니다! @hwangJi-dev 한번 확인해주세요!)

리스트가 업데이트되기 위해서는 viewWillAppear에서 서버통신 작업을 Reactor로 넘겨주는게 좋을 것 같아요~ setUpInitAction함수를 viewWillAppear로 옮겨주시면 감사하겠숩니당~~

2022-10-05 16:34 UTC, jane1choi commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Community/Reactor/CommunityMainReactor.swift
> +            return Observable.concat(self.requestMajorList(univID: 1, filterType: "all"))
@hwangJi-dev 굿 이거 일괄적으로 다 바꾸려고 했는데 바꿔서 푸시하겠습니다~!

2022-10-05 16:38 UTC, hwangJi-dev commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Community/Reactor/CommunityMainReactor.swift
> +            return Observable.concat(self.requestMajorList(univID: 1, filterType: "all"))
아 그러면은 이거 따로 이슈 파서 한번에 바꾸는게 좋을것같다!!!!!!

2022-10-05 16:39 UTC, jane1choi commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Community/VC/CommunityMainVC.swift
> +        reactor?.action.onNext(.viewWillAppear)
@hwangJi-dev 맞습니다! 싱글톤에 전역적으로 저장되는 리스트를 bind 메서드 (리액터가 주입되었을때 한번 호출) 에서만 조회되도록 하면 과방탭을 갔다가 다시 커뮤니티로 왔을때 리스트 갱신이 되지 않아 학과 무관 옵션이 사라지기 때문에 viewDidAppear에서 매번 리스트 조회를 하게 해주었고, 액션명 같은 경우 과방에서 viewWillAppear()에서 학과 리스트 요청을 해주었어서 리액터를 구성할때 `.viewWillAppear` 로 액션명을 정했었는데 기존 작업에 viewDidAppear()가 있어서 그 안에서 해주었습니다. 액션명을 더 직관적으로 바꿔야할 필요가 있다면 바꾸겠습니다!

2022-10-05 16:41 UTC, jane1choi commented on NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Xib/MajorTVC.swift
> +        }
@hwangJi-dev prepareForReuse 써서 재사용문제 없도록 하고 확인하긴했는데 확실한 처리 위해서 else문 추가 하도록 하겠습니다~ 조언 감사해용

2022-10-05 16:46 UTC, hwangJi-dev commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Community/VC/CommunityMainVC.swift
> +        reactor?.action.onNext(.viewWillAppear)
@jane1choi 학과 리스트 싱글톤 관련 논의하고 싶은 부분 슬랙에 글 남겨뒀어용 한번만 확인해줭!

2022-10-06 01:51 UTC, dev-madilyn approved these changes
확인했어용 ~ 이번 업뎃 끝나고 꼭... 리액터 공부한다 :)

2022-10-06 04:33 UTC, hwangJi-dev approved these changes
변수명 관련 리뷰 한번만 확인해쥬세용~ 진짜 수고했엉 ㅜㅜ!!!!!

2022-10-06 04:33 UTC, hwangJi-dev commented on NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Xib/HalfModalVC.swift
> +    var isHasOption: Bool = true
나중에 코드보면 어떤 옵션이지? 할수도 있을 것 같아서 `hasNoMajorOption`으로 변경하거나 너무 길면 "학과무관" 옵션임을 명시할 수 있는 변수명이면 훨씬 좋을 것 같아!

2022-10-06 04:41 UTC, jane1choi commented on NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Xib/HalfModalVC.swift
> +    var isHasOption: Bool = true
@hwangJi-dev 수정했습니다!! 조언 감사해요🥰
[7b6668e](https://github.com/TeamNado-Sunbae/NadoSunbae-iOS/pull/504/commits/7b6668e38801d1ed76f0b3bb1065fa2f9e7a86e5)

2022-10-06 05:11 UTC, hwangJi-dev commented on NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Xib/HalfModalVC.swift
> +    var isHasOption: Bool = true
> @hwangJi-dev 수정했습니다!! 조언 감사해요🥰 [7b6668e](https://github.com/TeamNado-Sunbae/NadoSunbae-iOS/pull/504/commits/7b6668e38801d1ed76f0b3bb1065fa2f9e7a86e5)

확인이용 ㅎㅎㅎ 고생했오!!

2022-10-06 07:03 UTC, merged