✨ [FEAT] 프로필 수정 뷰 수정사항 반영
TeamNado-Sunbae/NadoSunbae-iOS pull request #532
Opened 2022-10-11 07:32 UTC by jane1choi

## 🍎 관련 이슈
closed #509 

## 🍎 변경 사항 및 이유
프로필 수정 뷰의 UI 수정 사항을 반영했습니다.

## 🍎 PR Point
- 프로필 수정 뷰 바텀시트의 높이가 달라 present해주는 뷰에서 높이 지정을 할 수 있도록 코드를 수정했습니다.
- 프로필 수정 뷰의 경우 필요한 에셋이 없어 이벤트 로직 완성을 못했는데 디자인 파트에 요청해두었으니 추후에 이미지 전달까지 완료하도록 하겠습니다.
- 한줄소개 `textView` 추가 및 글자수 제한 기능을 구현했습니다.
- 제2전공 바텀시트의 경우 '미진입' 옵션이 있고 `univID`가 다를 경우 해당옵션의 `majorID`또한 다르기 때문에 `EditProfileVC`에서 학과리스트 요청 통신을 secondMajor filter를 걸어 통신을 한 번 더 해주었습니다.
- 커뮤니티 글쓰기 뷰에서 학과 무관 옵션의 경우 디폴트 MajorID 값을 박아두어서 유저가 선택안한 경우 해당 id값으로 요청이 가도록 했었는데 `univID`가 다를 경우 `majorID`또한 다르다는 걸 확인해서 싱글톤에 담아둔 id로 학교마다 다르게 구분되어 요청이 갈 수 있도록 코드를 수정했습니다.

**+** 프로필 수정 뷰 UI는 거의 완료했는데 (에셋 나오지 않은거 + 진입시기의 경우 정빈이가 어떻게 리스트에 넣었는지 확인을 못해서 요부분빼고), 프로필 수정 요청 기능 구현의 경우 담당자가 원래 정빈이었어서 요거 이어서 맡을지 아니면 제가 계속할지? 논의가 필요할 것 같습니당! @dev-madilyn 확인 한번 해주세여~!

## 📸 ScreenShot
- 프로필 수정 뷰 바텀시트 + 한줄소개 글자수 제한

https://user-images.githubusercontent.com/63277563/195022876-e46fdc46-562b-4e78-afd7-e1d24e8ad980.mp4

- 본전공, 제2전공 바텀시트 비교

https://user-images.githubusercontent.com/63277563/195022884-11689375-daea-43c8-8e49-f9311a632d2b.mp4

2022-10-11 14:41 UTC, dev-madilyn commented
> 프로필 수정 요청 기능 구현의 경우 담당자가 원래 정빈이었어서 요거 이어서 맡을지 아니면 제가 계속할지? 논의가 필요할 것 같습니당! @dev-madilyn 확인 한번 해주세여~!

@jane1choi "프로필 수정 요청 기능" 이라는 게 요청 request 말하는 건가? 이거랑 아마 저장버튼 활성화/비활성화 기능, 진입시기 안 될 것 같은데
진입시기는 SignUpMajorInfo뷰랑 똑같이 하면 되구... 저장버튼이랑 request 날리는 거는 모델 수정해야 해!

언니 이거 이어서 하는 거 혹시 부담됑 ??

2022-10-11 14:49 UTC, dev-madilyn approved these changes
확인이여 ~

2022-10-11 14:49 UTC, dev-jungbin commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ProfileSetting/VC/EditProfileVC.swift
> +    // HalfModalView를 present하는 메서드
여기 주석 /// 세 개로 통일해야 할 것 같아여 ~

2022-10-11 14:49 UTC, dev-jungbin commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ProfileSetting/VC/EditProfileVC.swift
> +        introTextView.rx.text.orEmpty
감사용 ~

2022-10-11 16:51 UTC, dev-madilyn commented
ㅎㅎ 작업한거 이 브랜치에 커밋 잘못 해서..,, 모두 revert 해주었습니당

2022-10-12 08:45 UTC, hwangJi-dev approved these changes
고생했어요~

2022-10-13 16:00 UTC, jane1choi commented
@hwangJi-dev @dev-madilyn 
바텀시트 UI 적용완료 + 프로필 사진 선택 시 데이터 전달 까지 완료했습니다!
커밋은 [687fac7](https://github.com/TeamNado-Sunbae/NadoSunbae-iOS/pull/532/commits/687fac7a0b3bda7e0c2301150d2449f4cce078c7) 부터 봐주세요~

2022-10-13 17:33 UTC, hwangJi-dev requested changes
리뷰 한번만 확인해주세요~

2022-10-13 17:33 UTC, hwangJi-dev commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ProfileSetting/VC/EditProfileImgModalVC.swift
> +        default:
요기 originalProfileImgID case number랑 profileImgBtn number랑 달라지는 이유가 무엇인가요?

2022-10-13 17:33 UTC, hwangJi-dev commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ProfileSetting/VC/EditProfileVC.swift
> +                selectedProfileImgID = 5
ID 숫자값이랑 UIImage name 숫자값이랑 같으니까 delegate 전달할 때 UIImage의 에셋이름중 숫자값을 넘기는건 어떨까요?

2022-10-14 04:46 UTC, dev-madilyn approved these changes
확인!

2022-10-14 04:46 UTC, dev-madilyn commented on NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ProfileSetting/VC/EditProfileImgModalVC.swift
> +        }
이부분 `completeBtn.isActivated = sender != defaultSelectedBtn`로 수정할 수 있을 것 같아여~!~

2022-10-15 11:08 UTC, hwangJi-dev approved these changes
확인했어요~ 고생했어!!

2022-10-17 07:38 UTC, merged